In [13]:
import numpy as np

def read_matrix_from_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        rows, cols = map(int, lines[0].split())
        matrix = np.array([list(map(int, line.split())) for line in lines[1:]])

    return matrix

# Чтение матриц из файлов
matrix1 = read_matrix_from_file(r'C:\\Users\\esh20\\OneDrive\\Рабочий стол\\HTML+MATH\\Uvarov-Nikita-6313-100503D-Lab1\\ParallProg\\matrix1.txt')
matrix2 = read_matrix_from_file(r'C:\\Users\\esh20\\OneDrive\\Рабочий стол\\HTML+MATH\\Uvarov-Nikita-6313-100503D-Lab1\\ParallProg\\matrix2.txt')

print("Матрица 1:\n", matrix1)
print("Матрица 2:\n", matrix2)

def write_matrix_to_file(file_path, matrix):
    with open(file_path, 'w') as file:
        file.write(f"{len(matrix)} {len(matrix[0])}\n")
        for row in matrix:
            file.write(' '.join(map(str, row)) + '\n')


# Умножение матриц
result_matrix = np.matmul(matrix1, matrix2)

# Запись результата в файл
write_matrix_to_file('result_matrix.txt', result_matrix)

print("Матрицы перемножены успешно, и результат записан в файл 'result_matrix.txt'.")
print("Result:\n", result_matrix)

Матрица 1:
 [[  4 100  98 ...  38  36  58]
 [ 16  18  66 ...   1  61  43]
 [ 17  23   7 ...  79  34  61]
 ...
 [  7  33  53 ...  18  14   9]
 [ 99  34  33 ...  14  24   3]
 [ 81   5  69 ...  81  73  11]]
Матрица 2:
 [[16  4 50 ... 55 96 36]
 [38 75 40 ... 21  6 90]
 [37 38 41 ... 22 91 32]
 ...
 [61 47 34 ... 80 20 25]
 [35 54 66 ... 69 37  7]
 [98 89 71 ... 70 78 50]]
